blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Questions and Help
    url: https://saucelabs.com/training-support
    about: Visit our support portal to review frequently asked questions, use cases, and submit questions.
  - name: ðŸ“ƒ Documentation Issue
    url: https://github.com/saucelabs/sauce-docs/issues/doc-error
    about: Report any inaccurate or missing content in a particular page or section.
  - name: ðŸ’¡ New Topic Suggestion
    url: https://github.com/saucelabs/sauce-docs/issue/new-doc
    about: Suggest an idea for new documentation topic!
