# Copyright 2019 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build, Test, and Deploy

on:
  pull_request:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-west1
  SERVICE_NAME: sauce-docs
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  build-and-deploy-to-cloud-run:
    name: Deploy to GCP Cloud Run
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      # Build and push image to Google Container Registry
      - name: Build Image
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
      # Deploy image to Cloud Run
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated \
            --port 3000

  saucectl-cypress:
    name: Run Testrunner Toolkit
    runs-on: ubuntu-latest
    needs: build-and-deploy
    container:
      image: saucelabs/stt-cypress-mocha-node:v0.1.3

    steps:
      # appears that checkout@v2 uses javascript which is not compatible
      # with the included node version in the container image.
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Workaround for container permissions
        run: sudo chown -R $USER:$(id -gn $USER) /github/home

      - name: Workaround for build permissions
        run: sudo chown -R $USER:$(id -gn $USER) /__w/sauce-docs/sauce-docs

      - name: Workaround for container folder
        run: sudo ln -s /home/seluser/.cache /github/home/.cache

      - name: Build Site and Run Sauce Pipeline Tests
        run: |
          saucectl run -c ./.sauce/config.yml
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions